spring:
  application:
    name: Trade Processor
kafka:
  bootstrapServers: localhost:9092
  consumerGroup: TRADE_GROUP
  inboundTopic: TRADE_FEED_IN
  outboundTopic: TRADE_FEED_OUT
  keySerializer: org.apache.kafka.common.serialization.StringSerializer
  valueSerializer: org.apache.kafka.common.serialization.StringSerializer
  keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
  valueDeserializer: org.apache.kafka.common.serialization.StringDeserializer
